<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Scufpad</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>Scufpad</AssemblyName>
    <LangVersion>preview</LangVersion>
    <PackageId>Scufpad</PackageId>
    <Authors>Chase Redmon</Authors>
    <Company>Scufpad</Company>
    <Product>Scufpad</Product>
  </PropertyGroup>

  <ItemGroup>
    <DirectPInvoke Include="libc"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="scufpad.Tests.Unit"/>
    <InternalsVisibleTo Include="scufpad.Tests.Integration"/>
  </ItemGroup>

</Project>
